[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
